import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { readFile } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * jsPDF's "pdfobjectnewwindow" output mode injects a <script> element that
 * loads PDFObject from a CDN — remote code execution this plugin never
 * uses (we only ever call output("arraybuffer")). This build plugin strips
 * that capability from the bundle entirely: the script-element creation is
 * replaced with a hard throw, so the code path cannot load external code.
 */
const stripDynamicScriptLoading = {
  name: "strip-dynamic-script-loading",
  setup(build) {
    build.onLoad({ filter: /[\\/]jspdf[\\/].*\.js$/ }, async (args) => {
      const contents = await readFile(args.path, "utf8");
      return {
        contents: contents.replaceAll(
          '.createElement("script")',
          '.createElement&&(()=>{throw new Error("Dynamic script loading is disabled in this build")})()',
        ),
        loader: "js",
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [stripDynamicScriptLoading],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
